default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: ror
  password: 1234
  host: localhost 

development:
  <<: *default
  database: sample_app_development

test:
  <<: *default
  database: sample_app_test
  
production:
  <<: *default
  database: sample_app_production
